### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by prasadreddyganji** [aws-samples/parallelcluster-monitoring-dashboard#5]
@laportad Does the jobs-details dashboard has capabilities to show individual job deatails. I have deployed it but it is showing the data of all the cores the nodes that are being utilized now but not individual jobs details.

**Comment by laportad** [comment]
You can use the Job dashboard to search the required job. You should also move the data and time in the dashboard to the job execution time.

**Comment by prasadreddyganji** [comment]
@laportad 

> You can use the Job dashboard to search the required job. You should also move the data and time in the dashboard to the job execution time.

The jobs-details dashboard is showing results for me , but not able to filter jobid. When i enter jobid it is showing no data and is redirecting to None dashboard and is showing all cores that are running. Let me know what part or exact location i need to debug for this jobs-details dashboard.

**Comment by gbts** [comment]
Same issue here. Filtering by jobid doesn't work and always resets back to None

**Comment by laportad** [comment]
I will try to reproduce the issue.

**Comment by laportad** [comment]
I found the reason of the issue and the last commit fix it.
